# Generated by Django 5.1.1 on 2024-09-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuhot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menu',
            new_name='menucold',
        ),
    ]
